[project]
name = "local-llm"
version = "0.1.0"
description = "A workshop on using local LLMs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=0.5.18",
    "ollama>=0.3.3",
]
