[project]
name = "local-llm"
version = "0.1.0"
description = "A workshop on using local LLMs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "chromadb>=0.5.18",
    "flask-cors>=5.0.0",
    "flask>=3.1.0",
    "ollama>=0.3.3",
    "requests>=2.32.3",
]
